// `claude-pointer install` and `claude-pointer claude` (quickstart.md "Setup").

import { spawn } from "node:child_process";
import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const HOST_NAME = "claude_pointer";
export const EXTENSION_ID = "claude-pointer@ohaukeboe";

export interface InstallOptions {
  home: string;
  configHome?: string;
  dataHome?: string;
  execPath: string;
  cliPath: string;
}

export interface InstallResult {
  manifestPath: string;
  wrapperPath: string;
  mcpConfigPath: string;
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export function mcpConfigPath(home: string, configHome?: string): string {
  return join(configHome ?? join(home, ".config"), "claude-pointer", "mcp.json");
}

export function install(o: InstallOptions): InstallResult {
  const dataHome = o.dataHome ?? join(o.home, ".local", "share");
  const wrapperPath = join(dataHome, "claude-pointer", "native-host");
  mkdirSync(dirname(wrapperPath), { recursive: true });
  writeFileSync(
    wrapperPath,
    `#!/bin/sh\n# Generated by claude-pointer install.\nexec ${shellQuote(o.execPath)} ${shellQuote(o.cliPath)} native-host\n`,
  );
  chmodSync(wrapperPath, 0o755);

  // Firefox reads user-level hosts from ~/.mozilla/native-messaging-hosts (also on NixOS).
  const manifestPath = join(o.home, ".mozilla", "native-messaging-hosts", `${HOST_NAME}.json`);
  mkdirSync(dirname(manifestPath), { recursive: true });
  writeFileSync(
    manifestPath,
    JSON.stringify(
      {
        name: HOST_NAME,
        description: "Claude Pointer bridge to Claude Code sessions",
        path: wrapperPath,
        type: "stdio",
        allowed_extensions: [EXTENSION_ID],
      },
      null,
      2,
    ) + "\n",
  );

  const mcpPath = mcpConfigPath(o.home, o.configHome);
  mkdirSync(dirname(mcpPath), { recursive: true });
  writeFileSync(
    mcpPath,
    JSON.stringify(
      { mcpServers: { "claude-pointer": { command: o.execPath, args: [o.cliPath, "channel"] } } },
      null,
      2,
    ) + "\n",
  );
  return { manifestPath, wrapperPath, mcpConfigPath: mcpPath };
}

export function claudeArgs(mcpPath: string, extra: string[]): string[] {
  return [
    "--mcp-config",
    mcpPath,
    "--dangerously-load-development-channels",
    "server:claude-pointer",
    ...extra,
  ];
}

export function runClaude(extra: string[]): Promise<number> {
  const home = process.env.HOME ?? "";
  const args = claudeArgs(mcpConfigPath(home, process.env.XDG_CONFIG_HOME), extra);
  return new Promise((resolve) => {
    const child = spawn("claude", args, { stdio: "inherit" });
    child.on("exit", (code) => resolve(code ?? 1));
    child.on("error", (e) => {
      process.stderr.write(`claude-pointer: cannot start claude: ${e.message}\n`);
      resolve(127);
    });
  });
}
